QT.hidapi_private.VERSION = 5.4.2
QT.hidapi_private.MAJOR_VERSION = 5
QT.hidapi_private.MINOR_VERSION = 4
QT.hidapi_private.PATCH_VERSION = 2
QT.hidapi_private.name = QHidApi
QT.hidapi_private.libs = $$QT_MODULE_LIB_BASE
QT.hidapi_private.includes = $$QT_MODULE_INCLUDE_BASE/QHidApi/5.4.2 $$QT_MODULE_INCLUDE_BASE/QHidApi/5.4.2/QHidApi
QT.hidapi_private.depends = hidapi
QT.hidapi_private.module_config = internal_module no_link
