QT.hidapi_private.VERSION = 0.1.0
QT.hidapi_private.MAJOR_VERSION = 0
QT.hidapi_private.MINOR_VERSION = 1
QT.hidapi_private.PATCH_VERSION = 0
QT.hidapi_private.name = QHidApi
QT.hidapi_private.libs = $$QT_MODULE_LIB_BASE
QT.hidapi_private.includes = $$QT_MODULE_INCLUDE_BASE/QHidApi/0.1.0 $$QT_MODULE_INCLUDE_BASE/QHidApi/0.1.0/QHidApi
QT.hidapi_private.depends = hidapi
QT.hidapi_private.module_config = internal_module no_link
