/* This file was generated by syncqt. */
#ifndef QT_QHIDAPI_VERSION_H
#define QT_QHIDAPI_VERSION_H

#define QHIDAPI_VERSION_STR "0.1.0"

#define QHIDAPI_VERSION 0x000100

#endif // QT_QHIDAPI_VERSION_H
